import argparse
import json
import os
import time
from pathlib import Path

import pandas as pd
import requests
from dotenv import load_dotenv
from tenacity import RetryError, retry, stop_after_attempt, wait_exponential
from tqdm import tqdm


ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_INPUT_FILE = ROOT_DIR / "data" / "01_prompts.jsonl"
DEFAULT_OUTPUT_JSONL = ROOT_DIR / "data" / "02_raw_responses.jsonl"
DEFAULT_OUTPUT_CSV = ROOT_DIR / "data" / "02_raw_responses.csv"
DEFAULT_ENV_CANDIDATES = [
    ROOT_DIR / "my.env",
    ROOT_DIR / ".env",
]
DEFAULT_MODELS = [
    "openai/gpt-4o-mini",
    "google/gemini-2.0-flash-001",
    "qwen/qwen-2.5-7b-instruct",
    "meta-llama/llama-3.1-8b-instruct",
]
DEFAULT_PILOT_LIMIT = 50
API_URL = "https://openrouter.ai/api/v1/chat/completions"


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Run OpenRouter inference on prompt requests generated by 01_data_prep.py. "
            "This script is the standard CLI entrypoint for Phase 2, and "
            "02_api_runner.ipynb is kept as an optional interactive testing notebook."
        )
    )
    parser.add_argument(
        "--mode",
        choices=["pilot", "full"],
        default="full",
        help="Use 'pilot' for a small test run or 'full' for the complete prompt set.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional task limit. If omitted, pilot mode uses 50 tasks and full mode uses all tasks.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from an existing JSONL file and skip completed request/model pairs.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files before starting a new run.",
    )
    parser.add_argument(
        "--input-file",
        type=Path,
        default=DEFAULT_INPUT_FILE,
        help="Path to the prompt JSONL file.",
    )
    parser.add_argument(
        "--output-jsonl",
        type=Path,
        default=DEFAULT_OUTPUT_JSONL,
        help="Path to the raw response JSONL output file.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=DEFAULT_OUTPUT_CSV,
        help="Path to the raw response CSV output file.",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="Optional env file containing OPENROUTER_API_KEY. Defaults to my.env, then .env.",
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=1.0,
        help="Delay between requests to reduce rate-limit pressure.",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=DEFAULT_MODELS,
        help="One or more OpenRouter model ids.",
    )
    return parser.parse_args()


def resolve_env_file(explicit_env_file):
    if explicit_env_file is not None:
        return explicit_env_file
    for candidate in DEFAULT_ENV_CANDIDATES:
        if candidate.exists():
            return candidate
    return None


def setup_env(explicit_env_file=None):
    env_file = resolve_env_file(explicit_env_file)
    if env_file is not None:
        load_dotenv(dotenv_path=env_file, override=True)

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENROUTER_API_KEY not found. Provide --env-file or create my.env/.env in the repo root."
        )

    env_label = str(env_file) if env_file is not None else "process environment"
    print(f"Loaded API credentials from: {env_label}")
    return api_key


def read_jsonl(path):
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def request_key(row, model_id):
    request_id = row.get("request_id") or row.get("item_id") or row.get("task_id") or "unknown_request"
    return f"{request_id}::{model_id}"


def select_tasks(all_tasks, mode, limit):
    if limit is None:
        limit = DEFAULT_PILOT_LIMIT if mode == "pilot" else len(all_tasks)
    limit = min(limit, len(all_tasks))
    return all_tasks[:limit]


def prepare_outputs(output_jsonl, output_csv, resume=False, overwrite=False):
    if resume and overwrite:
        raise ValueError("--resume and --overwrite cannot be used together.")

    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    if overwrite:
        if output_jsonl.exists():
            output_jsonl.unlink()
        if output_csv.exists():
            output_csv.unlink()
        return [], set()

    if output_jsonl.exists() or output_csv.exists():
        if not resume:
            raise FileExistsError(
                "Output files already exist. Use --resume to continue or --overwrite to start a fresh run."
            )

    existing_rows = read_jsonl(output_jsonl) if output_jsonl.exists() else []
    seen = {
        request_key(row, row.get("model_id", "unknown_model"))
        for row in existing_rows
        if row.get("model_id")
    }
    return existing_rows, seen


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=4, max=10))
def get_ai_response(api_key, model_id, prompt):
    headers = {
        "Authorization": f"Bearer {api_key.strip().lower() if api_key.startswith('SK-OR') else api_key.strip()}",
        "Content-Type": "application/json",
    }

    refined_prompt = (
        f"{prompt.strip()}\n\n"
        "IMPORTANT: Output ONLY the correct option letter (A, B, C, or D).\n"
        "Do NOT include brackets, periods, or any explanations.\n"
        "Just the single letter."
    )

    payload = {
        "model": model_id,
        "messages": [{"role": "user", "content": refined_prompt}],
        "temperature": 0,
        "max_tokens": 150,
    }

    response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
    if response.status_code != 200:
        raise RuntimeError(f"API Error {response.status_code}: {response.text}")

    res_data = response.json()
    message = res_data["choices"][0]["message"]
    content = message.get("content") or message.get("reasoning") or ""
    cleaned = str(content).strip().replace("[", "").replace("]", "")
    return cleaned if cleaned else "N/A"


def format_item_to_prompt(item):
    messages = item.get("messages", [])
    if messages:
        return messages[0].get("content", "")
    return ""


def append_jsonl(path, row):
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def export_csv(rows, output_csv):
    if not rows:
        print("No rows collected. CSV export skipped.")
        return
    pd.DataFrame(rows).to_csv(output_csv, index=False, encoding="utf-8-sig")
    print(f"Saved CSV output to: {output_csv}")


def check_balance(api_key):
    url = "https://openrouter.ai/api/v1/key"
    headers = {"Authorization": f"Bearer {api_key}"}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        data = response.json().get("data", {})
        print(
            "OpenRouter balance: "
            f"remaining {data.get('limit_remaining')} / total {data.get('limit')}"
        )
    except Exception as exc:
        print(f"Could not fetch balance information: {exc}")


def main():
    args = parse_args()
    api_key = setup_env(args.env_file)

    if not args.input_file.exists():
        raise FileNotFoundError(f"Input file not found: {args.input_file}")

    all_tasks = read_jsonl(args.input_file)
    tasks = select_tasks(all_tasks, args.mode, args.limit)
    results, seen_pairs = prepare_outputs(
        args.output_jsonl,
        args.output_csv,
        resume=args.resume,
        overwrite=args.overwrite,
    )

    total_possible = len(tasks) * len(args.models)
    completed_before_run = len(seen_pairs)

    print(f"Run mode: {args.mode}")
    print(f"Prompt file: {args.input_file}")
    print(f"Selected prompt requests: {len(tasks)} / {len(all_tasks)}")
    print(f"Models: {len(args.models)}")
    print(f"Potential request/model pairs: {total_possible}")
    if args.resume:
        print(f"Already completed pairs detected: {completed_before_run}")

    written_this_run = 0

    for model_id in args.models:
        print(f"\nProcessing model: {model_id}")
        progress = tqdm(tasks, desc=f"{model_id.split('/')[-1]}")

        for item in progress:
            pair_key = request_key(item, model_id)
            if pair_key in seen_pairs:
                continue

            prompt = format_item_to_prompt(item)
            current_id = item.get("request_id") or item.get("item_id") or "unknown_request"

            try:
                raw_answer = get_ai_response(api_key, model_id, prompt)
                output_item = item.copy()
                output_item.update(
                    {
                        "model_id": model_id,
                        "raw_response": raw_answer,
                    }
                )

                results.append(output_item)
                append_jsonl(args.output_jsonl, output_item)
                seen_pairs.add(pair_key)
                written_this_run += 1
                time.sleep(args.sleep_seconds)

            except RetryError as exc:
                real_exc = exc.last_attempt.exception() if hasattr(exc, "last_attempt") else exc
                print(f"Task failed after retries: {current_id} -> {real_exc}")
            except Exception as exc:
                print(f"Task failed: {current_id} -> {exc}")

    export_csv(results, args.output_csv)
    print(f"Rows available after run: {len(results)}")
    print(f"New rows written in this run: {written_this_run}")
    check_balance(api_key)


if __name__ == "__main__":
    main()
