import argparse
import json
import os
import time
from collections import Counter
from pathlib import Path

import pandas as pd
import requests
from dotenv import load_dotenv
from tenacity import RetryError, retry, stop_after_attempt, wait_exponential
from tqdm import tqdm


ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_INPUT_FILE = ROOT_DIR / "data" / "01_prompts.jsonl"
DEFAULT_OUTPUT_JSONL = ROOT_DIR / "data" / "02_raw_responses.jsonl"
DEFAULT_OUTPUT_CSV = ROOT_DIR / "data" / "02_raw_responses.csv"
DEFAULT_MMLU_OUTPUT_JSONL = ROOT_DIR / "data" / "02_raw_responses_MMLU_subjects.jsonl"
DEFAULT_MMLU_OUTPUT_CSV = ROOT_DIR / "data" / "02_raw_responses_MMLU_subjects.csv"
DEFAULT_ENV_CANDIDATES = [
    ROOT_DIR / "my.env.local",
    ROOT_DIR / ".env",
    ROOT_DIR / "my.env",
]
DEFAULT_MODELS = [
    "openai/gpt-4o-mini",
    "google/gemini-2.0-flash-001",
    "qwen/qwen-2.5-7b-instruct",
    "meta-llama/llama-3.1-8b-instruct",
]
DEFAULT_PILOT_LIMIT = 50
API_URL = "https://openrouter.ai/api/v1/chat/completions"
ANSWER_ONLY_INSTRUCTION = (
    "IMPORTANT: Output ONLY the correct option letter (A, B, C, or D).\n"
    "Do NOT include brackets, periods, or any explanations.\n"
    "Just the single letter."
)
PLACEHOLDER_API_KEYS = {
    "",
    "sk-or-v1-xxxxxxxxxxxxxxxxxxxxxxxxx",
    "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "your_openrouter_api_key_here",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Run OpenRouter inference on prompt requests generated by 01_data_prep.py. "
            "This standardized Phase 2 runner folds the logic previously split between "
            "02_api_runner.ipynb and 02_api_runner_mmlu.ipynb into one CLI entrypoint."
        )
    )
    parser.add_argument(
        "--mode",
        choices=["pilot", "full"],
        default="full",
        help="Use 'pilot' for a small test run or 'full' for the complete selected prompt set.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional task limit. If omitted, pilot mode uses 50 tasks and full mode uses all selected tasks.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume from an existing JSONL file and skip completed request/model pairs.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files before starting a new run.",
    )
    parser.add_argument(
        "--input-file",
        type=Path,
        default=DEFAULT_INPUT_FILE,
        help="Path to the prompt JSONL file.",
    )
    parser.add_argument(
        "--output-jsonl",
        type=Path,
        default=None,
        help="Path to the raw response JSONL output file. Defaults are inferred from the selected subset.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Path to the raw response CSV output file. Defaults are inferred from the selected subset.",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help=(
            "Optional env file containing OPENROUTER_API_KEY. "
            "Defaults to my.env.local, then .env, then the tracked my.env placeholder."
        ),
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=1.0,
        help="Delay between requests to reduce rate-limit pressure.",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=DEFAULT_MODELS,
        help="One or more OpenRouter model ids.",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=None,
        help="Optional dataset filter, for example: --datasets mmlu",
    )
    parser.add_argument(
        "--subjects",
        nargs="+",
        default=None,
        help="Optional subject filter, mainly for MMLU subset runs.",
    )
    parser.add_argument(
        "--templates",
        nargs="+",
        default=None,
        help="Optional prompt template filter.",
    )
    return parser.parse_args()


def resolve_env_file(explicit_env_file):
    if explicit_env_file is not None:
        return explicit_env_file
    for candidate in DEFAULT_ENV_CANDIDATES:
        if candidate.exists():
            return candidate
    return None


def is_placeholder_api_key(value):
    normalized = str(value or "").strip()
    if not normalized:
        return True
    if normalized in PLACEHOLDER_API_KEYS:
        return True
    return "xxxxxxxx" in normalized.lower()


def setup_env(explicit_env_file=None):
    env_file = resolve_env_file(explicit_env_file)
    if explicit_env_file is not None:
        load_dotenv(dotenv_path=env_file, override=True)
        api_key = os.getenv("OPENROUTER_API_KEY")
        if not api_key or is_placeholder_api_key(api_key):
            raise RuntimeError(
                "OPENROUTER_API_KEY not found in the explicit --env-file, or it still uses a placeholder value."
            )
        env_label = str(env_file)
        print(f"Loaded API credentials from: {env_label}")
        return api_key.strip()

    loaded_from = None
    for candidate in DEFAULT_ENV_CANDIDATES:
        if not candidate.exists():
            continue
        load_dotenv(dotenv_path=candidate, override=True)
        api_key = os.getenv("OPENROUTER_API_KEY")
        if api_key and not is_placeholder_api_key(api_key):
            loaded_from = candidate
            break

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key or is_placeholder_api_key(api_key):
        raise RuntimeError(
            "OPENROUTER_API_KEY not found. Provide --env-file or store a real key in my.env.local or .env."
        )

    env_label = str(loaded_from) if loaded_from is not None else "process environment"
    print(f"Loaded API credentials from: {env_label}")
    return api_key.strip()


def read_jsonl(path):
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def normalize_filters(values, lower=False):
    if not values:
        return None
    normalized = {str(value).strip() for value in values if str(value).strip()}
    if lower:
        normalized = {value.lower() for value in normalized}
    return normalized or None


def filter_tasks(all_tasks, datasets=None, subjects=None, templates=None):
    dataset_filter = normalize_filters(datasets, lower=True)
    subject_filter = normalize_filters(subjects, lower=False)
    template_filter = normalize_filters(templates, lower=False)

    filtered = []
    for task in all_tasks:
        dataset = str(task.get("dataset", "")).lower()
        subject = task.get("subject")
        template_name = task.get("template_name")

        if dataset_filter and dataset not in dataset_filter:
            continue
        if subject_filter and subject not in subject_filter:
            continue
        if template_filter and template_name not in template_filter:
            continue
        filtered.append(task)

    return filtered


def select_tasks(filtered_tasks, mode, limit):
    if limit is None:
        limit = DEFAULT_PILOT_LIMIT if mode == "pilot" else len(filtered_tasks)
    limit = min(limit, len(filtered_tasks))
    return filtered_tasks[:limit]


def should_use_mmlu_defaults(args):
    input_name = args.input_file.name.lower()
    dataset_filter = normalize_filters(args.datasets, lower=True)

    return (
        "mmlu" in input_name
        or bool(args.subjects)
        or (dataset_filter is not None and dataset_filter == {"mmlu"})
    )


def resolve_output_paths(args):
    default_jsonl = DEFAULT_MMLU_OUTPUT_JSONL if should_use_mmlu_defaults(args) else DEFAULT_OUTPUT_JSONL
    default_csv = DEFAULT_MMLU_OUTPUT_CSV if should_use_mmlu_defaults(args) else DEFAULT_OUTPUT_CSV

    output_jsonl = args.output_jsonl or default_jsonl
    output_csv = args.output_csv or default_csv
    return output_jsonl, output_csv


def request_key(row, model_id):
    request_id = row.get("request_id") or row.get("item_id") or row.get("task_id") or "unknown_request"
    return f"{request_id}::{model_id}"


def prepare_outputs(output_jsonl, output_csv, resume=False, overwrite=False):
    if resume and overwrite:
        raise ValueError("--resume and --overwrite cannot be used together.")

    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    if overwrite:
        if output_jsonl.exists():
            output_jsonl.unlink()
        if output_csv.exists():
            output_csv.unlink()
        return [], set()

    if output_jsonl.exists() or output_csv.exists():
        if not resume:
            raise FileExistsError(
                "Output files already exist. Use --resume to continue or --overwrite to start a fresh run."
            )

    existing_rows = read_jsonl(output_jsonl) if output_jsonl.exists() else []
    seen = {
        request_key(row, row.get("model_id", "unknown_model"))
        for row in existing_rows
        if row.get("model_id")
    }
    return existing_rows, seen


def add_answer_only_instruction(text):
    prompt = str(text or "").rstrip()
    if not prompt:
        return ANSWER_ONLY_INSTRUCTION
    return f"{prompt}\n\n{ANSWER_ONLY_INSTRUCTION}"


def build_api_messages(item):
    source_messages = item.get("messages")
    if isinstance(source_messages, list) and source_messages:
        messages = []
        for message in source_messages:
            if not isinstance(message, dict):
                continue
            role = str(message.get("role") or "user").lower()
            content = message.get("content")
            if content is None:
                continue
            messages.append({"role": role, "content": extract_text_content(content)})
    else:
        prompt = format_item_to_prompt(item)
        messages = [{"role": "user", "content": prompt}]

    if not messages:
        messages = [{"role": "user", "content": ""}]

    for index in range(len(messages) - 1, -1, -1):
        if messages[index]["role"] == "user":
            messages[index]["content"] = add_answer_only_instruction(messages[index]["content"])
            break
    else:
        messages.append({"role": "user", "content": ANSWER_ONLY_INSTRUCTION})

    return messages


def extract_text_content(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        chunks = []
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                chunks.append(str(part.get("text", "")))
            else:
                chunks.append(str(part))
        return "\n".join(chunk for chunk in chunks if chunk)
    if content is None:
        return ""
    return str(content)


def clean_response_text(text):
    cleaned = str(text).strip()
    if not cleaned:
        return "N/A"
    if cleaned.startswith("[") and cleaned.endswith("]"):
        cleaned = cleaned[1:-1].strip()
    if cleaned in {"A.", "B.", "C.", "D."}:
        cleaned = cleaned[0]
    return cleaned or "N/A"


def normalize_api_key(api_key):
    stripped = api_key.strip()
    if stripped.startswith("SK-OR"):
        return stripped.lower()
    return stripped


@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=4, max=10))
def get_ai_response(api_key, model_id, messages):
    headers = {
        "Authorization": f"Bearer {normalize_api_key(api_key)}",
        "Content-Type": "application/json",
    }

    payload = {
        "model": model_id,
        "messages": messages,
        "temperature": 0,
        "max_tokens": 150,
    }

    response = requests.post(API_URL, headers=headers, json=payload, timeout=30)
    if response.status_code != 200:
        raise RuntimeError(f"API Error {response.status_code}: {response.text}")

    res_data = response.json()
    message = res_data["choices"][0]["message"]
    content = message.get("content") or message.get("reasoning") or ""
    return clean_response_text(extract_text_content(content))


def format_item_to_prompt(item):
    messages = item.get("messages", [])
    if messages:
        return messages[0].get("content", "")
    return ""


def append_jsonl(path, row):
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def export_csv(rows, output_csv):
    if not rows:
        print("No rows collected. CSV export skipped.")
        return
    pd.DataFrame(rows).to_csv(output_csv, index=False, encoding="utf-8-sig")
    print(f"Saved CSV output to: {output_csv}")


def print_selection_summary(
    input_file,
    all_tasks,
    filtered_tasks,
    selected_tasks,
    models,
    output_jsonl,
    output_csv,
    resume,
    seen_pairs,
):
    dataset_counts = Counter(task.get("dataset", "unknown") for task in filtered_tasks)
    template_counts = Counter(task.get("template_name", "unknown") for task in filtered_tasks)
    subject_counts = Counter(task.get("subject") for task in filtered_tasks if task.get("subject"))
    total_possible = len(selected_tasks) * len(models)

    print(f"Prompt file: {input_file}")
    print(f"Filtered prompt requests: {len(filtered_tasks)} / {len(all_tasks)}")
    print(f"Selected prompt requests: {len(selected_tasks)}")
    print(f"Models: {len(models)}")
    print(f"Potential request/model pairs: {total_possible}")
    print(f"Output JSONL: {output_jsonl}")
    print(f"Output CSV: {output_csv}")
    if resume:
        print(f"Already completed pairs detected: {len(seen_pairs)}")
    if dataset_counts:
        print("Datasets:", ", ".join(f"{name}={count}" for name, count in sorted(dataset_counts.items())))
    if subject_counts:
        preview = ", ".join(f"{name}={count}" for name, count in sorted(subject_counts.items())[:6])
        suffix = "" if len(subject_counts) <= 6 else ", ..."
        print(f"Subjects: {preview}{suffix}")
    if template_counts:
        print("Templates:", ", ".join(f"{name}={count}" for name, count in sorted(template_counts.items())))


def check_balance(api_key):
    url = "https://openrouter.ai/api/v1/key"
    headers = {"Authorization": f"Bearer {normalize_api_key(api_key)}"}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        data = response.json().get("data", {})
        print(
            "OpenRouter balance: "
            f"remaining {data.get('limit_remaining')} / total {data.get('limit')}"
        )
    except Exception as exc:
        print(f"Could not fetch balance information: {exc}")


def main():
    args = parse_args()
    api_key = setup_env(args.env_file)

    if not args.input_file.exists():
        raise FileNotFoundError(f"Input file not found: {args.input_file}")
    if args.limit is not None and args.limit <= 0:
        raise ValueError("--limit must be a positive integer.")
    if args.sleep_seconds < 0:
        raise ValueError("--sleep-seconds must be non-negative.")

    output_jsonl, output_csv = resolve_output_paths(args)

    all_tasks = read_jsonl(args.input_file)
    filtered_tasks = filter_tasks(
        all_tasks,
        datasets=args.datasets,
        subjects=args.subjects,
        templates=args.templates,
    )
    if not filtered_tasks:
        raise ValueError("No prompt requests matched the selected filters.")

    tasks = select_tasks(filtered_tasks, args.mode, args.limit)
    results, seen_pairs = prepare_outputs(
        output_jsonl,
        output_csv,
        resume=args.resume,
        overwrite=args.overwrite,
    )

    print_selection_summary(
        input_file=args.input_file,
        all_tasks=all_tasks,
        filtered_tasks=filtered_tasks,
        selected_tasks=tasks,
        models=args.models,
        output_jsonl=output_jsonl,
        output_csv=output_csv,
        resume=args.resume,
        seen_pairs=seen_pairs,
    )

    written_this_run = 0

    for model_id in args.models:
        print(f"\nProcessing model: {model_id}")
        progress = tqdm(tasks, desc=f"{model_id.split('/')[-1]}")

        for item in progress:
            pair_key = request_key(item, model_id)
            if pair_key in seen_pairs:
                continue

            current_id = item.get("request_id") or item.get("item_id") or "unknown_request"

            try:
                raw_answer = get_ai_response(api_key, model_id, build_api_messages(item))
                output_item = item.copy()
                output_item.update(
                    {
                        "model_id": model_id,
                        "raw_response": raw_answer,
                    }
                )

                results.append(output_item)
                append_jsonl(output_jsonl, output_item)
                seen_pairs.add(pair_key)
                written_this_run += 1

                if args.sleep_seconds:
                    time.sleep(args.sleep_seconds)

            except RetryError as exc:
                real_exc = exc.last_attempt.exception() if hasattr(exc, "last_attempt") else exc
                print(f"Task failed after retries: {current_id} -> {real_exc}")
            except Exception as exc:
                print(f"Task failed: {current_id} -> {exc}")

    export_csv(results, output_csv)
    print(f"Rows available after run: {len(results)}")
    print(f"New rows written in this run: {written_this_run}")
    check_balance(api_key)


if __name__ == "__main__":
    main()
